<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Calendar.v3" Version="1.69.0.3746" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BackGroundService\HireMate.Notification.Unified.Interface\HireMate.Notification.Unified.Interface.csproj" />
    <ProjectReference Include="..\Common\HireMate.Common\HireMate.Common.csproj" />
    <ProjectReference Include="..\Hiremate.AiAgent.Service\Hiremate.AiAgent.Service.csproj" />
    <ProjectReference Include="..\HireMate.Common.Utils\HireMate.Common.Utils.csproj" />
    <ProjectReference Include="..\HireMate.DataManagement\HireMate.DataManagement.csproj" />
  </ItemGroup>

</Project>
