<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BackGroundService\HireMate.Notification.Unified.Interface\HireMate.Notification.Unified.Interface.csproj" />
  </ItemGroup>

</Project>
